version: '3.7'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=savdb
    ports:
      - "5432:5432"
    volumes:
      - ./docker/database/local/postgres/data:/var/lib/postgresql/data

  pgadmin:
    image:  dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_PASSWORD=mysecretpassword
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin:rw
    ports:
      - "8001:80"
